version: '2'
services:
  filebeat:
    image: nomkhonwaan/filebeat 
    container_name: filebeat 
    build: 
      context: .. 
      dockerfile: ./client/filebeat/Dockerfile
    restart: always
    volumes:
      - $PWD/../logs:/opt/logger/logs
      - $PWD/filebeat:/opt/filebeat:ro
    command: -c /opt/filebeat/filebeat.yml
  client:
    image: nomkhonwaan/client:latest
    container_name: client
    build:
      context: ..
      dockerfile: ./client/client/Dockerfile
    restart: always
    volumes:
      - $PWD/../logs:/opt/logger/logs
      - $PWD/../config.yml:/opt/logger/config.yml:ro
    command: -debug=1 -config-path=/opt/logger

networks:
  default:
    external:
      name: master_default
