# Call targets, you can add more URLs, it will be called every second each target.
targets:
  - url: http://httpbin.org/ip
    method: GET

# Default calls per second is 20, it should up to n but I'm not guarantee the request will done in time.
calls_per_second: 20

output_logs:
  # This is default date/time format pattern in golang,
  # for more information please see also https://golang.org/pkg/time/
  path: /opt/stresser/logs/stresser-2006-01-02.log
  # Required JSON format to be parsed in Logstash and Elasticsearch
  type: JSON