version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  logstash:
    image: nomkhonwaan/logstash
    container_name: logstash
    build: 
      context: ..
      dockerfile: ./master/logstash/Dockerfile
    volumes:
      - $PWD/logstash:/opt/logstash:ro
    ports: 
      - 5044:5044
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    command: -f /opt/logstash/logstash.conf
  kibana:
    image: kibana:latest
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch